### ISSUE TITLE
Voice Debug UI Issue

### ISSUE THREAD

**Issue by dhkatz** [BeardDesign1/Material-design-theme#13]
There is a small bug in the Users section of Voice Debug as can be seen [here](https://b.catgirlsare.sexy/Hkaz.png).

Selected user box is extremely bright compared to the rest of the theme.

**Comment by BeardDesign1** [comment]
I've seen this issue many times ant it takes 30s to fix but I always forget about it. for sure it'll be fixed in the next update.
