### ISSUE TITLE
In embeds, there's a 2px horizontal offset between text fields and their titles.

### ISSUE THREAD

**Issue by aetheryx** [BeardDesign1/Material-design-theme#15]
I'm not sure if it's intentional or not. I'd like to know why if it was. Absolutely love the skin otherwise!
I used ShareX to show the issue up close. I immediately noticed it when I saw an embed, but it's not **that** obvious. 

With the theme: http://i.imgur.com/36IER30.png(I highlighted the horizontal 2px offset with the arrow diagonally)
Without: http://i.imgur.com/AqCxJR8.png
I'm not sure if my explanation was clear enough, but in the 2nd screenshot the selected (blue) text/pixels are directly vertically aligned.

**Comment by BeardDesign1** [comment]
hey, it's intentionnal, but if it's bothering you that much I'll just delete it :3

**Comment by aetheryx** [comment]
It is bothering me quite a bit, yeah :P
If you can edit the actual skin that'd be pretty cool(not to just have it fixed, but for me to directly influence one of the best BD skins), but if not I don't mind you just giving me an edited version of the skin either. 
Thanks in advance!

**Comment by BeardDesign1** [comment]
fixed that a while ago
