### ISSUE TITLE
Incredibly difficult to see new grey ring around server icons

### ISSUE THREAD

**Issue by gdude2002** [BeardDesign1/Material-design-theme#18]
Have started missing out on swathes of conversations because of this one - the "new message" indicator has been replaced with a grey ring around the server icon. Unfortunately, I find this incredibly difficult to notice.

If we can't have the old notification circle icon back, can we at least give the ring a bright colour? Perhaps the same light-blue as the "Add a server" button, or maybe an orange?

**Comment by BeardDesign1** [comment]
other people have mentionned this to me, I'll make a more noticeable ring in the next update

**Comment by gdude2002** [comment]
How long will that be? This makes Discord very unusable for me.

Alternatively, could you provide a CSS snippet?

**Comment by gdude2002** [comment]
Hm, a small suggestion: If you're going to do rings, why not do something like the voice activity indicators? Bigger and a little thicker, though, obviously.

Could even colour-code them, I guess.

**Comment by gdude2002** [comment]
This is much better. Thank you!

![](https://dl.dropboxusercontent.com/s/tijtllpna18l51g/Discord_2017-03-25_12-41-46.png)
