### ISSUE TITLE
issue with the chat and more stuff

### ISSUE THREAD

**Issue by TheSpartaPT** [BeardDesign1/Material-design-theme#2]
if your discord theme is white the text box where you supposed to write on the chat gets white, the stuff you write stays white so you can't see anything you're typing, and the color of the message that appears before you type anything there is to light. You should try and see for yourself because it isn't the only thing that changes.

**Comment by TheSpartaPT** [comment]
also just noticed, you left connection info, connection info -> Debug, Edit Channel and When you click in someone on the right side bar or chat unedited.

**Comment by BeardDesign1** [comment]
That has been an issue for a long time and it would take me 2 mins to fix it, so yeah it'll be done in the next update ;)
Since then just set the discord theme to dark ^^
