### ISSUE TITLE
You don't have adequate padding.

### ISSUE THREAD

**Issue by ghost** [BeardDesign1/Material-design-theme#20]
You need padding on the right hand side when in guilds, the icons for settings when hovering and for other various icons are too close to the side, this can be fixed below.
`div.scroller.guild-channels {
    padding-right: 15px;
}
button.icon.icon-settings {
    margin-right: 15px;
}`

**Comment by BeardDesign1** [comment]
I tried your fix but I don't know what's your problem, it just looks weird that way, can you send me screenshots of how it looks for you?(with and without your fix)

**Comment by ghost** [comment]
Sadly missed your comment. What was fixed in my bit of code was providing padding to the right of the settings and link buttons in guilds as proper material design would dictate, instead of allowing it to touch the edges.
