### ISSUE TITLE
Channel list not being "stylised"

### ISSUE THREAD

**Issue by Snow-Pyon** [BeardDesign1/Material-design-theme#23]
Hey, I just updated my Discord (Canary) to the latest update and found that the channel list isn't being adapted to the theme as you can see in the following screenshot:
![image](https://cloud.githubusercontent.com/assets/23110519/26733330/e76d2614-4790-11e7-956f-5574f262330a.png)

**Comment by BeardDesign1** [comment]
fixed that with a recent update
