### ISSUE TITLE
Light version?

### ISSUE THREAD

**Issue by Leeo97one** [BeardDesign1/Material-design-theme#4]
GG for this theme, it's really well made. But I think a light version would be beautiful too. Is this planned?

**Comment by BeardDesign1** [comment]
sorry for the extremely late answer, I usually forget about the github issues, for a while it was planned but as of now I just think it would be too much work. maybe later in the year, I'll see but for now it's not planned.

**Comment by Leeo97one** [comment]
OK no problem!

**Comment by boswelja** [comment]
*maybe* ill make a fork of this later and try make a light version :)
If thats OK with @BeardDesign1 of course

**Comment by BeardDesign1** [comment]
I mean I'm ok with it but don't waste your time, I'm about to release a new update
